version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: department_management_system
    ports:
      - "5437:5432"       #захочется поменять, меняем левый(!) порт, доступ к бд jdbc:postgresql://localhost:5437/airline_db?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Europe/Moscow
    restart: unless-stopped
  pgadmin:  # если бд не подключается или что-то не так, можно подключить и посмотреть здесь, НЕ используем localhost, используем порт докера
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 111@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin

